name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Debug Node.js and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: |
          npm ci
          npm list --depth=0

      - name: Build
        run: |
          echo "Building the project..."
          npm run build:gh-pages
          echo "Build completed. Directory structure:"
          find dist -type f | sort

      - name: Verify build output
        run: |
          if [ ! -f "dist/index.html" ]; then
            echo "Error: index.html not found in dist directory!"
            ls -la dist/
            exit 1
          fi

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
